name: CROWN

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python
  - requests
  - urllib3
  - numpy
  - numba
  - pandas
  - pyarrow
  - scikit-learn
  - gemmi
  - joblib
  - matplotlib
  - seaborn
  - scipy
  - tqdm
  - python-dotenv
  - pip
  - setuptools
  - wheel
  - six
  - rdkit
  - openmm
  - openmmforcefields
  - openff-toolkit
  - pdbfixer
  - openbabel
  - mmseqs2
  - oddt
  - h5py
  - pytables
  - biopython
  - pip:
      - biopandas
      - freesasa
      - posebusters
